
---
# Vars for software added by Joost:
create_containers: 4
default_container_name: docker
default_container_image: alpine
default_container_command: sleep 1d
golang_gopath: "$HOME/workspace-go"
borg_encryption_passphrase: CHANGEME
borg_repository: m5vz9gp4@m5vz9gp4.repo.borgbase.com:repo
borg_source_directories:
  - /srv/www
  - /var/lib/automysqlbackup
borg_exclude_patterns:
  - /srv/www/old-sites
borg_retention_policy:
  keep_hourly: 3
  keep_daily: 7
  keep_weekly: 4
  keep_monthly: 6
ubuntu_docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
docker_users:
  - joost

# Geerlingguy mac-dev-playbook vars, disabled the osx specific ones:

downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
# configure_osx: true

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://gitlab.com/joostl/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/.dotfiles
dotfiles_files:
  - inputrc
  # - osx
  - bashrc
  - bigqueryrc
  - bin
  - gitconfig
  - gitignore
  - gitmessage
  - git_template
  - todo.cfg
  - tmux.conf
  - vim
  - vimrc
  - vimrc.bundles
  - zshenv
  - zshrc
  - zsh

# # Install packages from other package managers.
# # Note: You are responsible for making sure the required package managers are
# # installed, eg. through homebrew.
# composer_packages: []
# # - name: drush
# #   state: present # present/absent, default: present
# #   version: "^8.1" # default: N/A
# gem_packages: []
# # - name: bundler
# #   state: present # present/absent/latest, default: present
# #   version: "~> 1.15.1" # default: N/A
# npm_packages:
#   - name: lerna
#   - name: firebase-tools
#   - name: webpack
#   - name: webpack-cli
#   - name: eslint
#   - name: sqip


# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []